name: flutter_jayjay_starter
description: A powerful Flutter application starter template with premium features, in-app purchases, and ad integration.
version: 0.0.1
publish_to: 'none'

keywords:
  - flutter
  - template
  - starter
  - boilerplate
  - premium
  - in-app-purchase
  - admob
  - database
  - multi-language
  - theme
  - architecture

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_mobile_ads: ^4.0.0
  in_app_purchase: ^3.1.13
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/ 